"""upgrade marketplace_listing for import flow

Revision ID: 0d720c3427c6
Revises: baabf1d46caf
Create Date: 2026-02-15 10:42:01.930432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d720c3427c6'
down_revision: Union[str, Sequence[str], None] = 'baabf1d46caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    import_status_enum = sa.Enum('UNLINKED', 'LINKED', 'ARCHIVED', name='import_status_enum')
    import_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('marketplace_listings', sa.Column('external_id', sa.String(length=255), nullable=False))
    op.add_column('marketplace_listings', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('marketplace_listings', sa.Column('gtin', sa.String(length=50), nullable=True))
    op.add_column('marketplace_listings', sa.Column('import_status', import_status_enum, nullable=False))
    op.add_column('marketplace_listings', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('marketplace_listings', 'product_variant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('marketplace_listings', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_constraint(op.f('uq_listing_variant_per_marketplace'), 'marketplace_listings', type_='unique')
    op.create_index(op.f('ix_marketplace_listings_external_id'), 'marketplace_listings', ['external_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_gtin'), 'marketplace_listings', ['gtin'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_import_status'), 'marketplace_listings', ['import_status'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_marketplace'), 'marketplace_listings', ['marketplace'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_marketplace_sku'), 'marketplace_listings', ['marketplace_sku'], unique=False)
    op.create_unique_constraint('uq_external_listing_per_org', 'marketplace_listings', ['organization_id', 'marketplace', 'external_id'])
    op.drop_constraint(op.f('marketplace_listings_product_variant_id_fkey'), 'marketplace_listings', type_='foreignkey')
    op.create_foreign_key(None, 'marketplace_listings', 'product_variants', ['product_variant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    import_status_enum = sa.Enum('UNLINKED', 'LINKED', 'ARCHIVED', name='import_status_enum')
    import_status_enum.drop(op.get_bind(), checkfirst=True)
    op.add_column('marketplace_listings', sa.Column('marketplace_item_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'marketplace_listings', type_='foreignkey')
    op.create_foreign_key(op.f('marketplace_listings_product_variant_id_fkey'), 'marketplace_listings', 'product_variants', ['product_variant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_external_listing_per_org', 'marketplace_listings', type_='unique')
    op.drop_index(op.f('ix_marketplace_listings_marketplace_sku'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_marketplace'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_import_status'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_gtin'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_external_id'), table_name='marketplace_listings')
    op.create_unique_constraint(op.f('uq_listing_variant_per_marketplace'), 'marketplace_listings', ['marketplace_account_id', 'product_variant_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('marketplace_listings', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('marketplace_listings', 'product_variant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('marketplace_listings', 'raw_payload')
    op.drop_column('marketplace_listings', 'import_status')
    op.drop_column('marketplace_listings', 'gtin')
    op.drop_column('marketplace_listings', 'title')
    op.drop_column('marketplace_listings', 'external_id')
    # ### end Alembic commands ###
