"""add walmart feed tables

Revision ID: 12ec5b8c02ac
Revises: 933f30f2bf31
Create Date: 2026-03-09 14:00:50.783716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ec5b8c02ac'
down_revision: Union[str, Sequence[str], None] = '933f30f2bf31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('product_type', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('product_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_type')
    op.drop_column('marketplace_listings', 'product_type')
    # ### end Alembic commands ###
