"""added marketplace product content details

Revision ID: 23518c05b257
Revises: 49511231b1c4
Create Date: 2026-03-14 13:22:00.533983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23518c05b257'
down_revision: Union[str, Sequence[str], None] = '49511231b1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_title', sa.String(length=500), nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_description', sa.Text(), nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_item_id', sa.String(length=255), nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_url', sa.String(length=500), nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_customer_rating', sa.String(length=10), nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_num_reviews', sa.String(length=20), nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_marketplace_listings_marketplace_item_id'), 'marketplace_listings', ['marketplace_item_id'], unique=False)
    op.drop_column('marketplace_listings', 'url')
    op.drop_column('marketplace_listings', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('marketplace_listings', sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_marketplace_listings_marketplace_item_id'), table_name='marketplace_listings')
    op.drop_column('marketplace_listings', 'marketplace_keywords')
    op.drop_column('marketplace_listings', 'marketplace_num_reviews')
    op.drop_column('marketplace_listings', 'marketplace_customer_rating')
    op.drop_column('marketplace_listings', 'marketplace_images')
    op.drop_column('marketplace_listings', 'marketplace_url')
    op.drop_column('marketplace_listings', 'marketplace_item_id')
    op.drop_column('marketplace_listings', 'marketplace_description')
    op.drop_column('marketplace_listings', 'marketplace_title')
    op.drop_column('marketplace_listings', 'brand')
    # ### end Alembic commands ###
