"""add order management tables

Revision ID: 2a495fb689b8
Revises: b3c4d5e6f7a8
Create Date: 2026-02-21 14:52:51.480785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a495fb689b8'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('marketplace_account_id', sa.UUID(), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('customer_order_id', sa.String(length=255), nullable=True),
    sa.Column('order_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ACKNOWLEDGED', 'PARTIALLY_SHIPPED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='order_status_enum'), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shipping_method', sa.String(length=50), nullable=True),
    sa.Column('estimated_ship_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_account_id'], ['marketplace_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'marketplace', 'external_order_id', name='uq_org_marketplace_order')
    )
    op.create_index(op.f('ix_orders_external_order_id'), 'orders', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_orders_marketplace'), 'orders', ['marketplace'], unique=False)
    op.create_index(op.f('ix_orders_marketplace_account_id'), 'orders', ['marketplace_account_id'], unique=False)
    op.create_index('ix_orders_org_marketplace', 'orders', ['organization_id', 'marketplace'], unique=False)
    op.create_index('ix_orders_org_order_date', 'orders', ['organization_id', 'order_date'], unique=False)
    op.create_index('ix_orders_org_status', 'orders', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_organization_id'), 'orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.String(length=20), nullable=False),
    sa.Column('external_sku', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('product_variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ACKNOWLEDGED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='order_line_status_enum'), nullable=False),
    sa.Column('cancellation_reason', sa.String(length=100), nullable=True),
    sa.Column('tracking_carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('tracking_url', sa.String(length=1000), nullable=True),
    sa.Column('ship_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('raw_line_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'line_number', name='uq_order_line_number')
    )
    op.create_index(op.f('ix_order_lines_external_sku'), 'order_lines', ['external_sku'], unique=False)
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_lines_organization_id'), 'order_lines', ['organization_id'], unique=False)
    op.create_index(op.f('ix_order_lines_product_variant_id'), 'order_lines', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_order_lines_status'), 'order_lines', ['status'], unique=False)
    op.create_table('order_status_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_line_id', sa.UUID(), nullable=True),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_logs_order_id'), 'order_status_logs', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_status_logs_order_line_id'), 'order_status_logs', ['order_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_status_logs_order_line_id'), table_name='order_status_logs')
    op.drop_index(op.f('ix_order_status_logs_order_id'), table_name='order_status_logs')
    op.drop_table('order_status_logs')
    op.drop_index(op.f('ix_order_lines_status'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_product_variant_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_organization_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_external_sku'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_organization_id'), table_name='orders')
    op.drop_index('ix_orders_org_status', table_name='orders')
    op.drop_index('ix_orders_org_order_date', table_name='orders')
    op.drop_index('ix_orders_org_marketplace', table_name='orders')
    op.drop_index(op.f('ix_orders_marketplace_account_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_marketplace'), table_name='orders')
    op.drop_index(op.f('ix_orders_external_order_id'), table_name='orders')
    op.drop_table('orders')

    # Drop enum types
    sa.Enum(name='order_line_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='order_status_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
