"""extend product for PIM fields

Revision ID: 30ae69992fbf
Revises: 920022a75499
Create Date: 2026-02-17 14:58:34.186142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30ae69992fbf'
down_revision: Union[str, Sequence[str], None] = '920022a75499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('bullet_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('seo_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Manually create the PostgreSQL ENUM type before using it in a NOT NULL column
    product_status_enum = sa.Enum('DRAFT', 'READY', 'PUBLISHED', name='product_status_enum')
    product_status_enum.create(op.get_bind(), checkfirst=True)

    # Add the column with a server_default to satisfy existing rows
    op.add_column(
        'products',
        sa.Column('status', product_status_enum, server_default='DRAFT', nullable=False),
    )
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_column('products', 'status')
    op.drop_column('products', 'seo_keywords')
    op.drop_column('products', 'meta_description')
    op.drop_column('products', 'meta_title')
    op.drop_column('products', 'bullet_points')
    op.drop_column('products', 'description')
    op.drop_column('products', 'title')
    # Drop the ENUM type
    product_status_enum = sa.Enum('DRAFT', 'READY', 'PUBLISHED', name='product_status_enum')
    product_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
