"""add walmart feed tracking to marketplace listings

Revision ID: 49511231b1c4
Revises: f6e807170630
Create Date: 2026-03-11 12:41:29.393867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49511231b1c4'
down_revision: Union[str, Sequence[str], None] = 'f6e807170630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('last_feed_id', sa.String(length=255), nullable=True))
    op.add_column('marketplace_listings', sa.Column('last_feed_status', sa.String(length=50), nullable=True))
    op.add_column('marketplace_listings', sa.Column('last_feed_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_listings', 'last_feed_error')
    op.drop_column('marketplace_listings', 'last_feed_status')
    op.drop_column('marketplace_listings', 'last_feed_id')
    # ### end Alembic commands ###
