"""add subsubcategory_id to product_types

Revision ID: 4e5b2b6dc6af
Revises: 88daa70dfeea
Create Date: 2026-02-13 16:58:59.233269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5b2b6dc6af'
down_revision: Union[str, Sequence[str], None] = '88daa70dfeea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_types', sa.Column('subsubcategory_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('product_types_short_code_key'), 'product_types', type_='unique')
    op.create_index(op.f('ix_product_types_subsubcategory_id'), 'product_types', ['subsubcategory_id'], unique=False)
    # op.create_unique_constraint('uq_product_type_per_subsubcategory', 'product_types', ['subsubcategory_id', 'short_code'])
    # op.create_foreign_key(None, 'product_types', 'subsubcategories', ['subsubcategory_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_types', type_='foreignkey')
    op.drop_constraint('uq_product_type_per_subsubcategory', 'product_types', type_='unique')
    op.drop_index(op.f('ix_product_types_subsubcategory_id'), table_name='product_types')
    op.create_unique_constraint(op.f('product_types_short_code_key'), 'product_types', ['short_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('product_types', 'subsubcategory_id')
    # ### end Alembic commands ###
