"""Add Walmart report request models

Revision ID: 621d6bdabdcb
Revises: 4f1a5e05a515
Create Date: 2026-04-05 15:26:51.786589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621d6bdabdcb'
down_revision: Union[str, Sequence[str], None] = '4f1a5e05a515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walmart_report_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('marketplace_account_id', sa.UUID(), nullable=False),
    sa.Column('external_request_id', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('report_version', sa.String(length=10), nullable=False),
    sa.Column('data_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_account_id'], ['marketplace_accounts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walmart_report_requests_external_request_id'), 'walmart_report_requests', ['external_request_id'], unique=False)
    op.create_table('walmart_report_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('walmart_report_request_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['walmart_report_request_id'], ['walmart_report_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walmart_report_notifications')
    op.drop_index(op.f('ix_walmart_report_requests_external_request_id'), table_name='walmart_report_requests')
    op.drop_table('walmart_report_requests')
    # ### end Alembic commands ###
