"""added url for marketplace platform

Revision ID: 6715f7effe24
Revises: 12ec5b8c02ac
Create Date: 2026-03-09 14:27:39.202575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6715f7effe24'
down_revision: Union[str, Sequence[str], None] = '12ec5b8c02ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_listings', 'url')
    # ### end Alembic commands ###
