"""Add listing quality data columns

Revision ID: 79783539640e
Revises: 621d6bdabdcb
Create Date: 2026-04-10 18:47:19.172678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79783539640e'
down_revision: Union[str, Sequence[str], None] = '621d6bdabdcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('listing_quality_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('marketplace_listings', sa.Column('listing_quality_score', sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_listings', 'listing_quality_score')
    op.drop_column('marketplace_listings', 'listing_quality_data')
    # ### end Alembic commands ###
