"""add is_system_admin to users

Revision ID: 7bbbfbaf4b61
Revises: 9906d9406132
Create Date: 2026-02-13 14:39:54.267125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbbfbaf4b61'
down_revision: Union[str, Sequence[str], None] = '9906d9406132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_system_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_system_admin')
    # ### end Alembic commands ###
