"""add_region_to_marketplace_account

Revision ID: 7cbf80e38ecc
Revises: 2a495fb689b8
Create Date: 2026-02-27 10:29:55.227305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbf80e38ecc'
down_revision: Union[str, Sequence[str], None] = '2a495fb689b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_accounts', sa.Column('region', sa.String(length=50), server_default='US', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_accounts', 'region')
    # ### end Alembic commands ###
