"""add google taxonomy model

Revision ID: 88daa70dfeea
Revises: 7bbbfbaf4b61
Create Date: 2026-02-13 14:48:07.799729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88daa70dfeea'
down_revision: Union[str, Sequence[str], None] = '7bbbfbaf4b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_taxonomies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_taxonomy_id', sa.Integer(), nullable=False),
    sa.Column('full_path', sa.String(length=500), nullable=False),
    sa.Column('level_depth', sa.Integer(), nullable=False),
    sa.Column('is_leaf', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_taxonomy_id', name='uq_google_taxonomy_id')
    )
    op.create_index(op.f('ix_google_taxonomies_google_taxonomy_id'), 'google_taxonomies', ['google_taxonomy_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_taxonomies_google_taxonomy_id'), table_name='google_taxonomies')
    op.drop_table('google_taxonomies')
    # ### end Alembic commands ###
