"""add gtin to products

Revision ID: 920022a75499
Revises: 0d720c3427c6
Create Date: 2026-02-16 14:26:56.224878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920022a75499'
down_revision: Union[str, Sequence[str], None] = '0d720c3427c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_listings', 'marketplace_item_id')
    op.add_column('products', sa.Column('gtin', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_products_gtin'), 'products', ['gtin'], unique=False)
    op.create_unique_constraint('uq_product_gtin_per_org', 'products', ['organization_id', 'gtin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_gtin_per_org', 'products', type_='unique')
    op.drop_index(op.f('ix_products_gtin'), table_name='products')
    op.drop_column('products', 'gtin')
    op.add_column('marketplace_listings', sa.Column('marketplace_item_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
