"""removed relationship product_type in listings

Revision ID: 933f30f2bf31
Revises: a7b5b880357f
Create Date: 2026-03-09 12:37:47.430871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933f30f2bf31'
down_revision: Union[str, Sequence[str], None] = 'a7b5b880357f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
