"""added product_type in listings

Revision ID: a7b5b880357f
Revises: d01f1f2d9ee6
Create Date: 2026-03-09 12:32:24.373777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7b5b880357f'
down_revision: Union[str, Sequence[str], None] = 'd01f1f2d9ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('product_type', sa.String(length=255), nullable=True))
    op.drop_column('marketplace_listings', 'marketplace_inventory_updated_at')
    op.drop_column('marketplace_listings', 'marketplace_shelf_keywords')
    op.drop_column('marketplace_listings', 'marketplace_inventory_quantity')
    op.drop_column('marketplace_listings', 'marketplace_bullet_points')
    op.drop_column('marketplace_listings', 'marketplace_images')
    op.drop_column('marketplace_listings', 'marketplace_videos')
    op.drop_column('marketplace_listings', 'marketplace_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('marketplace_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_videos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_images', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_bullet_points', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_inventory_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_shelf_keywords', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_inventory_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('marketplace_listings', 'product_type')
    # ### end Alembic commands ###
