"""enforce product_type hierarchy integrity

Revision ID: baabf1d46caf
Revises: 4e5b2b6dc6af
Create Date: 2026-02-13 17:21:12.384528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baabf1d46caf'
down_revision: Union[str, Sequence[str], None] = '4e5b2b6dc6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_types', 'subsubcategory_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('uq_product_type_per_subsubcategory', 'product_types', ['subsubcategory_id', 'short_code'])
    op.create_foreign_key(None, 'product_types', 'subsubcategories', ['subsubcategory_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_types', type_='foreignkey')
    op.drop_constraint('uq_product_type_per_subsubcategory', 'product_types', type_='unique')
    op.alter_column('product_types', 'subsubcategory_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
