"""add marketplace override content

Revision ID: bf6476554786
Revises: 30ae69992fbf
Create Date: 2026-02-17 15:21:38.287578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf6476554786'
down_revision: Union[str, Sequence[str], None] = '30ae69992fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('override_title', sa.String(length=255), nullable=True))
    op.add_column('marketplace_listings', sa.Column('override_description', sa.Text(), nullable=True))
    op.add_column('marketplace_listings', sa.Column('override_bullet_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_listings', 'override_bullet_points')
    op.drop_column('marketplace_listings', 'override_description')
    op.drop_column('marketplace_listings', 'override_title')
    # ### end Alembic commands ###
