"""add_marketplace_bullet_points_to_listings

Revision ID: c6fa92fda2e4
Revises: 23518c05b257
Create Date: 2026-03-16 10:14:07.899688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6fa92fda2e4'
down_revision: Union[str, Sequence[str], None] = '23518c05b257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('marketplace_bullet_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_listings', 'marketplace_bullet_points')
    # ### end Alembic commands ###
