"""add_default_address_and_label_tracking_columns

Revision ID: f4f0079c312e
Revises: c6fa92fda2e4
Create Date: 2026-03-27 10:41:52.740604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4f0079c312e'
down_revision: Union[str, Sequence[str], None] = 'c6fa92fda2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_accounts', sa.Column('default_from_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('marketplace_accounts', sa.Column('default_return_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('label_tracking_number', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('label_carrier', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('label_carrier_service_type', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('label_tracking_url', sa.String(length=1000), nullable=True))
    op.add_column('organizations', sa.Column('from_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('organizations', sa.Column('return_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'return_address')
    op.drop_column('organizations', 'from_address')
    op.drop_column('orders', 'label_tracking_url')
    op.drop_column('orders', 'label_carrier_service_type')
    op.drop_column('orders', 'label_carrier')
    op.drop_column('orders', 'label_tracking_number')
    op.drop_column('marketplace_accounts', 'default_return_address')
    op.drop_column('marketplace_accounts', 'default_from_address')
    # ### end Alembic commands ###
